---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: ptq
  - name: version

outputs:
  - name: build-output

run:
  path: ptq/ci/tasks/build.sh
