---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/cloudfoundry-cli
    tag: 'latest'

inputs:
- name: ptq
- name: artifact
- name: version

outputs:
- name: prepare-cf-output

params:
  CF_API_URL:
  CF_SKIP_SSL:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_APP_NAME:
  CF_APP_HOST:

run:
  path: ptq/ci/tasks/prepare-cf.sh
