---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  CF_MANIFEST_HOST: ptq

inputs:
  - name: ptq-repo
  - name: app-release
  - name: version

outputs:
  - name: prepare-manifest

run:
  path: ptq-repo/ci/tasks/prepare-manifest.sh
  args: [
    --input-dir, app-release,
    --output-dir, prepare-manifest,
    --version-file, version/number,
    --input-manifest, ptq-repo/manifest.yml,
    --artifactId, ptq,
    --packaging, jar
  ]