---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: ptq
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-final-output

run:
  path: ptq/ci/tasks/prepare-final.sh
