---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: ptq-repo
  - name: app-release

run:
  path: ptq-repo/ci/tasks/test.sh