---
cf-dev-url: https://api.system.52.176.40.186.cf.pcfazure.com
cf-dev-user: swomack@pivotal.io
cf-dev-password: pivotal123!
cf-dev-org: it-org
cf-dev-space: dev

cf-prod-url: http://api.system.pcf-apps.net
cf-prod-user: swomack@pivotal.io
cf-prod-password: pivotal1
cf-prod-org: it-org
cf-prod-space: prod