---
cf-dev-url: fhhcsdfcom
cf-dev-user: swomack@pivotal.io
cf-dev-password: no
cf-dev-org: it-org
cf-dev-space: dev

cf-prod-url: https://fug
cf-prod-user: adminoa
cf-prod-password: blard
cf-prod-org: it-org
cf-prod-space: prod
