---
cf-dev-url: https://api.system.52.176.40.186.cf.pcfazure.com
cf-dev-user: swomack@pivotal.io
cf-dev-password: pivotal123!
cf-dev-org: it-org
cf-dev-space: dev

cf-prod-url: https://api.system.13.90.33.125.cf.pcfazure.com
cf-prod-user: admin
cf-prod-password: zvfrgxn-l4xtWYrDfYxTgSegTfdsdGYX
cf-prod-org: it-org
cf-prod-space: prod