---
resources:
- name: source-code
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}

- name: app-release
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: processed-transactions-query-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: cf-dev
  type: cf
  source:
    api: {{cf-dev-url}}
    username: {{cf-dev-user}}
    password: {{cf-dev-password}}
    organization: {{cf-dev-org}}
    space: {{cf-dev-space}}
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-prod-url}}
    username: {{cf-prod-user}}
    password: {{cf-prod-password}}
    organization: {{cf-prod-org}}
    space: {{cf-prod-space}}
    skip_cert_check: true

jobs:
- name: ptq-dev
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/tasks/build.yml
  - put: app-release
    params: { file: build-output/target/processed-transactions-query-*.jar }
  - put: cf-dev
    params:
      current_app_name: mastercard-ess-query
      manifest: source-code/manifest.yml
      path: build-output/target/processed-transactions-query-0.0.1-SNAPSHOT.jar

- name: ptq-qa
  plan:
    - get: app-release
      passed: [ ptq-dev ]
      trigger: true
    - task: uat
      file: build-output/ci/tasks/uat.yml
    - put: cf-prod
      params:
        current_app_name: mastercard-ess-query
        manifest: uat-output/manifest.yml
        path: uat-output/target/processed-transactions-query-0.0.1-SNAPSHOT.jar